# Generated by Django 5.2.1 on 2025-06-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used Like New', 'Used Like New'), ('Good', 'Good'), ('Acceptable', 'Acceptable')], max_length=50),
        ),
    ]
