# Generated by Django 5.1.6 on 2025-07-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used Like New', 'Used Like New'), ('Good', 'Good'), ('Acceptable', 'Acceptable'), ('Poor', 'Poor')], max_length=50),
        ),
    ]
