# Generated by Django 5.2.5 on 2025-11-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_book_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='requester_accepted',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='requester_paid',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='requester_received',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='responder_accepted',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='responder_paid',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='responder_received',
        ),
        migrations.AddField(
            model_name='trade',
            name='requester_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='responder_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
