# Generated by Django 5.2.5 on 2025-11-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_address_user_address_line_user_county_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='county',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='trade',
            name='requester_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Accepted', max_length=20),
        ),
    ]
