# Generated by Django 5.2.5 on 2025-11-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_county_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_for_trade',
            field=models.BooleanField(default=False),
        ),
    ]
