# Generated by Django 5.2.5 on 2025-11-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_book_available_for_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_for_trade',
            field=models.BooleanField(default=True),
        ),
    ]
